#!/usr/bin/env python3
"""Fine-tune a small YOLO detector on the single class ``eur_pallet_base``.

Starts from COCO-pretrained weights (transfer learning); the weights are downloaded by
Ultralytics on first use. Everything runs locally; no images leave the machine.

Examples::

    # first real model (CPU works; a CUDA GPU is ~20x faster)
    python training/train.py --dataset dataset --model yolo11n.pt --imgsz 640 --epochs 150 --name v1

    # quick smoke test of the pipeline on synthetic data
    python training_tools/make_synthetic_dataset.py --out /tmp/synth
    python training/train.py --dataset /tmp/synth --epochs 3 --imgsz 320 --name smoke

The best weights end up in ``runs/detect/<name>/weights/best.pt`` (git-ignored). Next:
``training/evaluate.py`` and ``training/export_model.py``.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

CLASS_NAME = "eur_pallet_base"
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

# Augmentation tuned for side views of pallet lines: strong brightness/saturation changes
# (sun, shadow, wet wood), mild geometry (phone roughly level), horizontal flips (lines look
# the same mirrored), never vertical flips (pallets are always below the stacks).
AUGMENTATION = dict(
    hsv_h=0.015,
    hsv_s=0.6,
    hsv_v=0.5,
    degrees=3.0,
    translate=0.1,
    scale=0.5,
    shear=2.0,
    perspective=0.0005,
    flipud=0.0,
    fliplr=0.5,
    mosaic=1.0,
    mixup=0.0,
    close_mosaic=10,
)


def count_images(folder: Path) -> int:
    return sum(1 for p in folder.glob("*") if p.suffix.lower() in IMAGE_EXTENSIONS) if folder.exists() else 0


def write_dataset_yaml(dataset: Path) -> Path:
    """Writes dataset/dataset.yaml with an absolute path so training works from any cwd."""
    dataset = dataset.resolve()
    lines = [
        "# Generated by training/train.py",
        f"path: {dataset.as_posix()}",
        "train: images/train",
        "val: images/val",
    ]
    if count_images(dataset / "images" / "test"):
        lines.append("test: images/test")
    lines += ["names:", f"  0: {CLASS_NAME}", ""]
    yaml_path = dataset / "dataset.yaml"
    yaml_path.write_text("\n".join(lines))
    return yaml_path


def pick_device(requested: str) -> str:
    if requested:
        return requested
    import torch

    if torch.cuda.is_available():
        return "0"
    if getattr(torch.backends, "mps", None) is not None and torch.backends.mps.is_available():
        return "mps"
    return "cpu"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dataset", type=Path, default=Path("dataset"), help="dataset root with images/ and labels/")
    ap.add_argument("--model", default="yolo11n.pt",
                    help="starting weights: yolo11n.pt (default), yolo26n.pt, yolo11s.pt, or a previous best.pt")
    ap.add_argument("--imgsz", type=int, default=640, help="training image size (export size can be smaller)")
    ap.add_argument("--epochs", type=int, default=150)
    ap.add_argument("--batch", type=int, default=16)
    ap.add_argument("--patience", type=int, default=40, help="stop after this many epochs without improvement")
    ap.add_argument("--device", default="", help="'' = auto (cuda/mps/cpu), or e.g. 'cpu', '0'")
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--project", default="runs/detect")
    ap.add_argument("--name", default="pallet")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--resume", action="store_true", help="resume the last interrupted run of --name")
    args = ap.parse_args(argv)

    n_train = count_images(args.dataset / "images" / "train")
    n_val = count_images(args.dataset / "images" / "val")
    print(f"dataset {args.dataset}: {n_train} train / {n_val} val images")
    if n_train == 0 or n_val == 0:
        print("ERROR: need images in dataset/images/train and dataset/images/val "
              "(see training_tools/split_dataset.py)", file=sys.stderr)
        return 2
    if n_train < 100:
        print("warning: fewer than 100 training images - expect a weak model; see docs/DATA_COLLECTION.md")
    yaml_path = write_dataset_yaml(args.dataset)

    from ultralytics import YOLO

    if args.resume:
        last = Path(args.project) / args.name / "weights" / "last.pt"
        model = YOLO(str(last))
        model.train(resume=True)
    else:
        model = YOLO(args.model)
        model.train(
            data=str(yaml_path),
            imgsz=args.imgsz,
            epochs=args.epochs,
            batch=args.batch,
            patience=args.patience,
            device=pick_device(args.device),
            workers=args.workers,
            project=args.project,
            name=args.name,
            seed=args.seed,
            plots=True,
            **AUGMENTATION,
        )
    best = Path(model.trainer.best)
    metrics = getattr(model.trainer, "metrics", {}) or {}
    print("\nfinal validation:", {k: round(float(v), 4) for k, v in metrics.items() if "metrics/" in k})
    print(f"best weights: {best}")
    print("next steps:\n"
          f"  python training/evaluate.py --weights {best} --dataset {args.dataset}\n"
          f"  python training/export_model.py --weights {best} --imgsz 416 --out model/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
